version: 0.2

phases:
  install:
    commands:
      - echo Install Terraform
      - wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip
      - uzip ./terraform_0.12.26_linux_amd64.zip
  build:
    commands:
      - echo Run Terraform Init
      
